### ISSUE TITLE
Future of vue-loader

### ISSUE THREAD

**Issue by tomcastleman** [JeffreyWay/laravel-elixir-vue#1]
Hi @JeffreyWay ,

Thanks for your great work with elixir 6.

Forgive me if I have misunderstood something or am jumping the gun: is the webpack component loader `vue-loader` on which this package is based deprecated?

The [vue-loader-example repo](https://github.com/vuejs/vue-loader-example/) states:

"Deprecated in favor of [vue-cli](https://github.com/vuejs/vue-cli) and [webpack vue-cli template](https://github.com/vuejs-templates/webpack)."

Is the plan to move to using `vue-cli` under the hood for template compilation?

Cheers,

Tom

**Comment by kauhat** [comment]
I think `vue-loader` is still good. It seems like it's only the example repo that's being "deprecated" - `vue-loader` still a dependency in the templates used by the `vue-cli` project.

Had me confused as well!
