### ISSUE TITLE
Importing an ES6 .js module into a .vue file works incorrectly with Elixir 6

### ISSUE THREAD

**Issue by Mottokrosh** [JeffreyWay/laravel-elixir-vue#11]
See https://laracasts.com/discuss/channels/vue/importing-an-es6-js-module-into-a-vue-file-fails-with-elixir-6 for the details.

Essentially, if `import Thing from './Thing.js';`, `Thing` is `{ default: Thing }`.

**Comment by Mottokrosh** [comment]
And if this is actually an issue with vue-loader, I apologise for posting it here!

**Comment by laracasts** [comment]
This should have been fixed with 0.1.7. Can you make sure you have that version installed?

**Comment by Mottokrosh** [comment]
You are absolutely correct, sir. I had 0.1.6. Updated and that fixed it. Many thanks!
