### ISSUE TITLE
Vue 2.0 support

### ISSUE THREAD

**Issue by Skysplit** [JeffreyWay/laravel-elixir-vue#14]
As [VueJS 2.0 is here](https://medium.com/the-vue-point/vue-2-0-is-here-ef1f26acf4b8#.o5qw91a2o) its support would be nice to have.

Probably only `vue` and `vue-hot-reload-api` require update.

**Comment by Skysplit** [comment]
Probably major version needs to be changed as well, because of compatibility changes with current [laravel/laravel package.json](https://github.com/laravel/laravel/blob/master/package.json#L12)

**Comment by d13r** [comment]
It seems there is a replacement package:

https://github.com/vuejs/laravel-elixir-vue-2

Since it's in the Vue.js organisation it looks official.

**Comment by mstralka** [comment]
That package worked for me too
