### ISSUE TITLE
Specifying style language in vue templates

### ISSUE THREAD

**Issue by tomcastleman** [JeffreyWay/laravel-elixir-vue#2]
In my `.vue` template I am trying to specify the style language as per v5:

```
<style lang="sass">
</style>
```

However elixir 6 gives this error:

```
ERROR in ./resources/assets/js/components/Foo.vue
Module not found: Error: Can't resolve 'sass' in '/full/path/to/resources/assets/js/components/Foo'
 @ ./resources/assets/js/components/Foo.vue 2:0-205
```

Do I need to pull in another module, configure the `vue-style-loader` for sass, or is this currently unsupported?

Thanks

**Comment by JeffreyWay** [comment]
Vue Loader lets you use practically any pre-processor. So, yes, you'd pull in that package.

http://vue-loader.vuejs.org/en/configurations/pre-processors.html
