### ISSUE TITLE
Import doesn't work in .vue file

### ISSUE THREAD

**Issue by michellaurent** [JeffreyWay/laravel-elixir-vue#9]
With Laravel 5.3 and the new elixir version using webpack, I have the following issue.

If I put the following code in my app.js, it works fine.

```
import square from './components/utils/test.js';
alert(square(2));
```

If I put the same code in my example.vue code, it doesn't work.

```
<script>
    import square from './utils/test.js';
    alert(square(3));

    export default {
        ready() {
            //alert(square(2));
            console.log('Component ready.')
        }
    }
</script>
```

**Comment by michellaurent** [comment]
Following vue-loader documentation, it looks like we need to add a babel-loader if we import .js file ...

http://vue-loader.vuejs.org/en/features/es2015.html

**Comment by JeffreyWay** [comment]
Closing this in favor of your PR.
